import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';

export interface PurchaseOrderPdfData {
  poNumber: string;
  issueDate: Date;
  organizationName: string;
  vendorName: string;
  vendorEmail: string;
  vendorAddress?: string;
  items: Array<{ name: string; quantity: number; unitPrice: number; total: number }>;
  subtotal: number;
  tax: number;
  grandTotal: number;
  deliveryDate?: Date;
  paymentTerms?: string;
  aiSummary?: string;
}

/**
 * Generates a Purchase Order PDF in memory and returns a Buffer.
 * Uses PDFKit; stream is piped into a PassThrough and collected into a buffer
 * so it can be uploaded to Cloudinary/S3 or emailed as an attachment.
 */
export function generatePurchaseOrderPdf(data: PurchaseOrderPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const stream = new PassThrough();
    const chunks: Buffer[] = [];

    stream.on('data', (chunk) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);
    doc.pipe(stream);

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text('PURCHASE ORDER', { align: 'right' });
    doc.fontSize(10).font('Helvetica').fillColor('#555')
      .text(data.organizationName, { align: 'right' })
      .moveDown(1.5);

    doc.fillColor('#000').fontSize(11).font('Helvetica-Bold').text(`PO Number: ${data.poNumber}`);
    doc.font('Helvetica').text(`Issue Date: ${data.issueDate.toDateString()}`);
    if (data.deliveryDate) doc.text(`Expected Delivery: ${data.deliveryDate.toDateString()}`);
    doc.moveDown();

    doc.font('Helvetica-Bold').text('Vendor Details');
    doc.font('Helvetica').text(data.vendorName);
    doc.text(data.vendorEmail);
    if (data.vendorAddress) doc.text(data.vendorAddress);
    doc.moveDown();

    // Table header
    const tableTop = doc.y + 10;
    const col = { name: 50, qty: 280, price: 350, total: 450 };
    doc.font('Helvetica-Bold');
    doc.text('Item', col.name, tableTop);
    doc.text('Qty', col.qty, tableTop);
    doc.text('Unit Price', col.price, tableTop);
    doc.text('Total', col.total, tableTop);
    doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke();

    let y = tableTop + 25;
    doc.font('Helvetica');
    data.items.forEach((item) => {
      doc.text(item.name, col.name, y, { width: 220 });
      doc.text(String(item.quantity), col.qty, y);
      doc.text(item.unitPrice.toFixed(2), col.price, y);
      doc.text(item.total.toFixed(2), col.total, y);
      y += 22;
    });

    doc.moveTo(50, y + 5).lineTo(550, y + 5).stroke();
    y += 15;
    doc.text(`Subtotal: ${data.subtotal.toFixed(2)}`, col.price, y);
    y += 18;
    doc.text(`Tax: ${data.tax.toFixed(2)}`, col.price, y);
    y += 18;
    doc.font('Helvetica-Bold').text(`Grand Total: ${data.grandTotal.toFixed(2)}`, col.price, y);
    doc.font('Helvetica');

    if (data.paymentTerms) {
      doc.moveDown(3);
      doc.font('Helvetica-Bold').text('Payment Terms');
      doc.font('Helvetica').text(data.paymentTerms);
    }

    if (data.aiSummary) {
      doc.moveDown(1);
      doc.font('Helvetica-Bold').text('Summary (AI Generated)');
      doc.font('Helvetica').fontSize(9).fillColor('#444').text(data.aiSummary);
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#999').text('Generated by VendorFlow AI', { align: 'center' });

    doc.end();
  });
}
